# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 🚀 Deploy website sabbaddini on push on master

on:
  push:
    branches: [ "master" ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:        
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: ♲ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 🔨 Build Project
        id: builddeploy
        run: |
            npm cache clean --force
            npm install
            npm run build
        env:
            NODE_OPTIONS: ${{ '--max_old_space_size=5048' }}
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
            server: ${{ secrets.SERVER_SABBA_DEPLOY }}
            username: ${{ secrets.USER_SABBA_DEPLOY }}
            password: ${{ secrets.PWD_SABBA_DEPLOY }}
            local-dir: ./dist/portafolio-angular/browser/
            server-dir: /
            port: 21
